version: "3.4"
services:
    web:
        build: ./LeagueOfBets
        image: "localhost:5000/leagueofbets_web"
        ports:
            - "10080:80"
            - "10443:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTPS_PORT=10443
            - ASPNETCORE_URLS=https://+443;http://+80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=dev
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Core.ssl.pfx    
        networks:
            - global
            #- identity-1
            #- matches-1
        volumes:
            - ${APPDATA}\ASP.NET\Https:/root/.aspnet/https:ro
        depends_on:
            - identity
            - matches_api
    identity:
        build: ./Identity
        image: "localhost:5000/leagueofbets_identity"
        ports:
            - "20080:80"
            - "20443:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development            
            - ASPNETCORE_HTTPS_PORT=20443
            - ASPNETCORE_URLS=https://+443;http://+80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=dev
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Core.ssl.pfx
        networks:
            - global
            #- identity-1
            #- identity-internal
        volumes:
            - ${APPDATA}\ASP.NET\Https:/root/.aspnet/https:ro
        depends_on:
            - identity_sql
    identity_sql:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        ports:
            - "21433:1433"
        environment:
            - SA_PASSWORD=DeVeL0PeR
            - ACCEPT_EULA="Y"
        networks:
            - global
            #- identity-internal
        volumes:
            - identity-sqlvolume:/var/opt/mssql
    matches_api:
        build: 
            context: ./Matches/
            target: final-api
        image: "localhost:5000/leagueofbets_matches_api"
        ports:
            - "38080:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        networks:
            - global
            #- identity-1
            #- matches-1
            #- matches-internal
        depends_on:
            - matches_sql
    matches_worker:
        build:
            context: ./Matches/
            target: final-worker
        image: "localhost:5000/leagueofbets_matches_worker"
        networks:
            - global
            #- matches-internal
        depends_on:
            - matches_sql
            - bets_event_queue
    matches_sql:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        ports:
            - "31433:1433"
        environment:
            - SA_PASSWORD=DeVeL0PeR
            - ACCEPT_EULA="Y"
        networks:
            - global
            #- matches-internal
        volumes:
            - matches-sqlvolume:/var/opt/mssql
    bets_api:
        build:
            context: ./Bets/
            target: final-api
        image: "localhost:5000/leagueofbets_bets_api"
        ports:
            - "48080:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        networks:
            - global
            #- identity-1
            #- bets-1
            #- bets-internal
        depends_on:
            - bets_sql
    bets_worker:
        build:
            context: ./Bets/
            target: final-worker
        image: "localhost:5000/leagueofbets_bets_worker"
        networks:
            - global
            #- bets-internal
        depends_on:
            - bets_sql
            - bets_event_queue
    bets_sql:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        ports:
            - "41433:1433"
        environment:
            - SA_PASSWORD=DeVeL0PeR
            - ACCEPT_EULA="Y"
        networks:
            - global
            #- bets-internal
        volumes:
            - bets-sqlvolume:/var/opt/mssql
    bets_event_queue:
      image: "rabbitmq:3.6.14-management"
      ports:
          - "5672:5672"
          - "15672:15672"
      networks:
          - global
networks:
    global:
    #identity-1:
    #matches-1:
    #identity-internal:
    #matches-internal:
volumes:
    identity-sqlvolume:
    matches-sqlvolume:
    bets-sqlvolume: